package org.openmrs.module.callflows.api.service;

import org.openmrs.module.callflows.api.domain.CallFlow;
import org.openmrs.module.callflows.api.exception.CallFlowAlreadyExistsException;

import java.util.List;

/**
 * Service to manage CallFlows
 *
 * @author bramak09
 * @see org.openmrs.module.callflows.api.domain.CallFlow
 */
public interface CallFlowService {

    /**
     * Create a call flow in the system.
     * Validates the call flow name to ensure that it contains only alphanumeric characters
     * as special characters have special meaning during call flow execution
     *
     * @param callflow the call flow object to be saved
     * @return the callflow with id as generated by the database
     * @throws CallFlowAlreadyExistsException if a duplicate call flow with the same name already exists
     * @throws IllegalArgumentException       if the call flow name does not contain only alphanumeric characters
     */
    CallFlow create(CallFlow callflow) throws CallFlowAlreadyExistsException;

    /**
     * Updates a call flow in the system.
     * If the name of the call flow is being changed, it cannot be the same as that of an existing call flow
     * and special characters cannot be used in the name of the callflow as they have special significance during call flow execution
     *
     * @param callflow the call flow object to be updated
     * @return the callflow object
     * @throws CallFlowAlreadyExistsException if a duplicate callflow with the same name already exists
     * @throws IllegalArgumentException       if the call flow is not retrievable or does not contain only alphanumeric characters
     */
    CallFlow update(CallFlow callflow) throws CallFlowAlreadyExistsException;

    /**
     * Find all callflows that start with a specific name
     *
     * @param prefix a search term that is used to search for callflows
     * @return a list of found callflows
     */
    List<CallFlow> findAllByNamePrefix(String prefix);

    /**
     * Find a callflow by the given name
     *
     * @param name to search by
     * @return the callflow corresponding to the passed name
     * @throws IllegalArgumentException if the callflow cannot be found with the given name
     */
    CallFlow findByName(String name);

    /**
     * Deletes a callflow
     *
     * @param id of the callflow to delete
     * @throws IllegalArgumentException if no callflow with the given id exists
     */
    void delete(Integer id);
}
